#!/bin/bash

# Author : Doeraene Anthony

name=$(basename $0)
data=data/XXXL_data.txt

if [ "$#" -lt 1 ]; then
    echo "Usage : $name <cca> [reno-friendly-enabled = false]"
    exit 1
fi

cca=$1
cca=${cca,,}

if [ "$2" == "true" ] && [ "$cca" == "cubic" ]; then
    reno_friendly_disabled=""
    logs=/shared/$name/cubic_reno_friendly_enabled
else
    reno_friendly_disabled="--reno-friendly-disabled"
    logs=/shared/$name/$cca
fi

logs_keys=/shared/keys.txt

mkdir /shared/$name 2> /dev/null
mkdir $logs 2> /dev/null

# remove the previous configurations
./connect router1 "tc qdisc del dev eth1 root" > /dev/null 

# send data on the link using $cca
./connect router1 "/impair_itf eth1 10ms 8Mbit 20ms" > /dev/null 
./connect client1 "cd /home && /venv/bin/python src/client.py $data --host 10.0.1.1 -v 1 -c $cca --log-dir $logs --keylog-file $logs_keys -n $cca $reno_friendly_disabled"