#!/bin/bash

# Author : Doeraene Anthony

name=$(basename $0)

if [ "$#" -ne 1 ]; then
    echo "Usage : $name <cca>"
    exit 1
fi

cca=$1

data=data/XXL_data.txt

logs=/shared/$name/${cca}_iperf
logs_keys=/shared/keys.txt

mkdir /shared/$name 2> /dev/null
mkdir /shared/$name/${cca}_iperf 2> /dev/null

# remove the previous configurations
./connect router1 "tc qdisc del dev eth1 root" > /dev/null

# add a fixed bandwidth on router1
./connect router1 "/impair_itf eth1 5ms 8Mbit 50ms" > /dev/null

./connect client1 "cd /home && /venv/bin/python src/client.py $data --host 10.0.1.1 -v 1 -c $cca --log-dir $logs --keylog-file $logs_keys -n $cca"&
./connect client2 "iperf -c 10.0.1.2"&