#!/bin/bash

# Author : Doeraene Anthony

data=data/XXL_data.txt

name=$(basename $0)
logs=/shared/$name
logs_keys=/shared/keys.txt

mkdir /shared/$name 2> /dev/null

# remove the previous configurations
./connect router1 "tc qdisc del dev eth1 root" > /dev/null 

# set a huge buffer, with a fixed window
# BW = (cwnd / rtt) * 8 = (10000 / 0.04) * 8 = 2 Mbps, so if buffer can accept more than this, no problem
# buffer can accept a 4Mbps flow, so there is indeed no problem
./connect router1 "/impair_itf eth1 20ms 8Mbit 40ms" > /dev/null 
./connect client1 "cd /home && /venv/bin/python src/client.py $data --host 10.0.1.1 -v 1 -c nothing --log-dir $logs --keylog-file $logs_keys -s 10000 -n no_CCA"