#!/bin/bash

# Author : Doeraene Anthony

name=$(basename $0)

if [ "$#" -ne 1 ]; then
    echo "Usage : $name <cca>"
    exit 1
fi

cca=$1
data=data/XXL_data.txt

logs=/shared/$name/$cca
logs_keys=/shared/keys.txt

rtt1="13ms"
rtt2="80ms"

mkdir /shared/$name 2> /dev/null
mkdir /shared/$name/$cca 2> /dev/null

# remove the previous configurations
./connect router1 "tc qdisc del dev eth1 root" > /dev/null

# add a huge delay on router1
./connect router1 "/impair_itf eth1 $rtt1 8Mbit 20ms" > /dev/null 
./connect client1 "cd /home && /usr/bin/python3.10 src/client.py $data --host 10.0.1.1 -v 1 -c $cca --log-dir $logs --keylog-file $logs_keys -n $rtt1"

# reset router
./connect router1 "tc qdisc del dev eth1 root" > /dev/null 

# add an even greater delay on router1
./connect router1 "/impair_itf eth1 $rtt2 8Mbit 20ms" > /dev/null 
./connect client2 "cd /home && /usr/bin/python3.10 src/client.py $data --host 10.0.1.2 -v 1 -c $cca --log-dir $logs --keylog-file $logs_keys -n $rtt2"
