#!/bin/bash

# Author : Doeraene Anthony

name=$(basename $0)

if [ "$#" -ne 1 ]; then
    echo "Usage : $name <cca>"
    exit 1
fi

cca=$1
data=data/huge_data.txt

logs=/shared/$name/$cca
logs_keys=/shared/keys.txt

mkdir /shared/$name 2> /dev/null
mkdir /shared/$name/$cca 2> /dev/null

# remove the previous configurations
./connect router1 "tc qdisc del dev eth1 root" > /dev/null 

# add a fixed bandwidth on router1
./connect router1 "tc qdisc add dev eth1 root handle 1: tbf rate 8192kbit latency 5ms burst 256000" > /dev/null

# send the data for the 2 clients
./connect client1 "cd /home && /venv/bin/python src/client.py $data --host 10.0.1.1 -v 1 -c nothing --log-dir $logs --keylog-file $logs_keys -s 1000000 -n no_CCA"&
./connect client2 "cd /home && /venv/bin/python src/client.py $data --host 10.0.1.2 -v 1 -c $cca --log-dir $logs --keylog-file $logs_keys -n $cca"&