#!/bin/bash

# Author : Doeraene Anthony

ask_confirmation(){
    msg=$1
    yes=$2
    no=$3
    echo "$msg [Y/N]"
    read resp
    # convert to lower case
    resp=${resp,,}
    if [ "$resp" == "y" ]; then
        $yes
    else
        $no
    fi
}
is_red_hat(){
    test -f /etc/redhat-release
}

is_fedora(){
    test -n "$(cat /etc/os-release | grep fedora)"
}

enable_firewall(){
    echo "Restarting firewall..."
    sudo systemctl start firewalld
}

# delete the created files
rm -rf lab/client1
rm -rf lab/client2
rm -rf lab/server1
rm -rf lab/server2
rm -rf lab/main
rm -rf lab/router1
rm -rf lab/router2
rm lab/server1.logs 2> /dev/null
rm lab/server2.logs 2> /dev/null
sudo rm -rf lab/shared


# shutdown kathara
cd lab && sudo kathara lclean

if [ "$?" -ne 0 ]; then
    echo "Failed to shutdown lab, try the following commands, or just restart docker:

    sudo systemctl restart docker
    cd lab && sudo kathara lclean
    "
fi

if is_red_hat || is_fedora ; then
    echo "Fedora/Red-hat system detected"
    ask_confirmation "Do you want to start again your firewall ?" \
    'enable_firewall' \
    ':' # do nothing if don't accept
fi