#!/bin/bash

# Author : Doeraene Anthony

router="router1"
client="client1"
server="10.0.1.1"

kathara exec -d lab $router -- "sh -c \"/impair_itf eth1 10ms 8Mbit 40ms\"" > /dev/null

out=$(kathara exec -d lab $client -- "sh -c \"iperf -c $server\"" | grep "bits/sec")

bw=$(echo "$out" | cut -d" " -f10)
unit=$(echo "$out" | cut -d" " -f11)

if [ "$unit" != "Mbits/sec" ]; then
    echo "Invalid order of unit : $unit"
    exit 1
fi
if (( $(echo "$bw > 9" | bc -l) )); then
    echo "Too much bandwidth allocated : $bw $unit"
    exit 1
elif (( $(echo "$bw < 7" | bc -l) )); then
    echo "Not enough bandwidth allocated : $bw $unit"
    exit 1
fi

kathara exec -d lab $router -- "sh -c \"tc qdisc del dev eth1 root\""

echo "Bandwidth correctly limited to ~8Mbps"

exit 0